source 'https://rubygems.org'

gem 'dotenv'
gem 'pg'
gem 'activerecord'
gem 'activesupport'
gem 'activerecord-postgis-adapter'
gem 'terminal-table'
gem 'enumerate_it'

group :development, :test do
  gem 'pry-byebug'
end

group :test do
  gem 'rspec'
  gem 'shoulda'
  gem 'fabrication'
  gem 'database_cleaner'
  gem 'faker'
end
